### PR TITLE
Feature/support nav2018 changes

### PR DESCRIPTION
**Pull request by wortho**
This PR updates the NAV ETW profiler to support changes made to the events in NAV 2018. MS have stated that the events may continue to change in the future so this is a temporary fix.

### CODE REVIEW

**Comment by ShadowXVII** [comment]
Nice, thanks for updating.

Are there object types for the other new AL types, i.e. TableExtension, and even Enum/EnumExtension?
I'm assuming these compile down to objects too.

**Comment by wortho** [comment]
> Nice, thanks for updating.
> 
> Are there object types for the other new AL types, i.e. TableExtension, and even Enum/EnumExtension?
> I'm assuming these compile down to objects too.

Not that I am aware of. I got the updated list of object types from MS.

/David

**Comment by wortho** [comment]
> Ist there a newer version for business central? 
No I have not yet been able to get the updated events for Business Central. I have not been able to try it myself as the event provider is not installed in the docker image for BC. 
I have asked the MS Dynamics team for help.

**Comment by jwikman** [comment]
@wortho  Any reason that this PR is not merged yet?

**Comment by wortho** [comment]
> @wortho Any reason that this PR is not merged yet?

I am waiting for someone else to try it out and approve it.

**Comment by peterelmqvist** [comment]
> > @wortho Any reason that this PR is not merged yet?
> 
> I am waiting for someone else to try it out and approve it.

@wortho I have tested this on a NAV2018 and it works fine. I have only tested the "Updates Payload Indexes and removes references to UserName field." which was the main reason for it not working in NAV2018 due to changes in the ETW-manifest. This would most likly be the same for later CUs of NAV2016 and NAV2017 since the change in the ETW-manifest is due to GDPR-compliance. Based on that this would be considered a breaking change.

I have not been able to verify the "Support new NAV object types." nor if it works for Business Central On-Prem but I'm using this PR at a customer right now to measure perf.

**Comment by wortho** [comment]
> > Ist there a newer version for business central?

Check out the new branch https://github.com/wortho/EtwPerformanceProfiler/tree/feature/support-BC

**Pull request merged**
